/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-signal_hound
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SIGNAL_HOUND_API_H
#define INCLUDED_SIGNAL_HOUND_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_signal_hound_EXPORTS
#define SIGNAL_HOUND_API __GR_ATTR_EXPORT
#else
#define SIGNAL_HOUND_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SIGNAL_HOUND_API_H */
