/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bb_series.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d97264b044ac30be88722e046d2ae473)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/signal_hound/bb_series.h>
// pydoc.h is automatically generated in the build directory
#include <bb_series_pydoc.h>

void bind_bb_series(py::module& m)
{

    using bb_series = ::gr::signal_hound::bb_series;


    py::class_<bb_series,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<bb_series>>(m, "bb_series", D(bb_series))

        .def(py::init(&bb_series::make),
             py::arg("center"),
             py::arg("reflevel"),
             py::arg("decimation"),
             py::arg("bandwidth"),
             py::arg("purge"),
             D(bb_series, make))


        .def("set_center",
             &bb_series::set_center,
             py::arg("center"),
             D(bb_series, set_center))


        .def("set_reflevel",
             &bb_series::set_reflevel,
             py::arg("reflevel"),
             D(bb_series, set_reflevel))


        .def("set_decimation",
             &bb_series::set_decimation,
             py::arg("decimation"),
             D(bb_series, set_decimation))


        .def(
            "set_purge", &bb_series::set_purge, py::arg("purge"), D(bb_series, set_purge))


        .def("set_bandwidth",
             &bb_series::set_bandwidth,
             py::arg("bandwidth"),
             D(bb_series, set_bandwidth))

        ;
}
