/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sm_series.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(93d555963dfd60fc7ff406a9a6148fa5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/signal_hound/sm_series.h>
// pydoc.h is automatically generated in the build directory
#include <sm_series_pydoc.h>

void bind_sm_series(py::module& m)
{

    using sm_series = ::gr::signal_hound::sm_series;


    py::class_<sm_series,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<sm_series>>(m, "sm_series", D(sm_series))

        .def(py::init(&sm_series::make),
             py::arg("center"),
             py::arg("reflevel"),
             py::arg("atten"),
             py::arg("decimation"),
             py::arg("swfilter"),
             py::arg("purge"),
             py::arg("bandwidth"),
             py::arg("type"),
             py::arg("hostAddr"),
             py::arg("deviceAddr"),
             py::arg("port"),
             D(sm_series, make))


        .def("set_center",
             &sm_series::set_center,
             py::arg("center"),
             D(sm_series, set_center))


        .def("set_reflevel",
             &sm_series::set_reflevel,
             py::arg("reflevel"),
             D(sm_series, set_reflevel))


        .def(
            "set_atten", &sm_series::set_atten, py::arg("atten"), D(sm_series, set_atten))


        .def("set_decimation",
             &sm_series::set_decimation,
             py::arg("decimation"),
             D(sm_series, set_decimation))


        .def("set_swfilter",
             &sm_series::set_swfilter,
             py::arg("swfilter"),
             D(sm_series, set_swfilter))


        .def(
            "set_purge", &sm_series::set_purge, py::arg("purge"), D(sm_series, set_purge))


        .def("set_bandwidth",
             &sm_series::set_bandwidth,
             py::arg("bandwidth"),
             D(sm_series, set_bandwidth))


        .def("set_type", &sm_series::set_type, py::arg("type"), D(sm_series, set_type))


        .def("set_hostAddr",
             &sm_series::set_hostAddr,
             py::arg("hostAddr"),
             D(sm_series, set_hostAddr))


        .def("set_deviceAddr",
             &sm_series::set_deviceAddr,
             py::arg("hostAddr"),
             D(sm_series, set_deviceAddr))


        .def("set_port", &sm_series::set_port, py::arg("port"), D(sm_series, set_port))

        ;
}
