/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sp_series.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(754ac786fcb14de5e2cd3802248d14a1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/signal_hound/sp_series.h>
// pydoc.h is automatically generated in the build directory
#include <sp_series_pydoc.h>

void bind_sp_series(py::module& m)
{

    using sp_series = ::gr::signal_hound::sp_series;


    py::class_<sp_series,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<sp_series>>(m, "sp_series", D(sp_series))

        .def(py::init(&sp_series::make),
             py::arg("reflevel"),
             py::arg("atten"),
             py::arg("center"),
             py::arg("decimation"),
             py::arg("swfilter"),
             py::arg("bandwidth"),
             py::arg("purge"),
             D(sp_series, make))


        .def("set_center",
             &sp_series::set_center,
             py::arg("center"),
             D(sp_series, set_center))


        .def("set_reflevel",
             &sp_series::set_reflevel,
             py::arg("reflevel"),
             D(sp_series, set_reflevel))


        .def(
            "set_atten", &sp_series::set_atten, py::arg("atten"), D(sp_series, set_atten))


        .def("set_decimation",
             &sp_series::set_decimation,
             py::arg("decimation"),
             D(sp_series, set_decimation))


        .def("set_swfilter",
             &sp_series::set_swfilter,
             py::arg("swfilter"),
             D(sp_series, set_swfilter))


        .def(
            "set_purge", &sp_series::set_purge, py::arg("purge"), D(sp_series, set_purge))


        .def("set_bandwidth",
             &sp_series::set_bandwidth,
             py::arg("bandwidth"),
             D(sp_series, set_bandwidth))

        ;
}
