/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vsg_series.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cac25b8444a6fc6137a731a29213e5cb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/signal_hound/vsg_series.h>
// pydoc.h is automatically generated in the build directory
#include <vsg_series_pydoc.h>

void bind_vsg_series(py::module& m)
{

    using vsg_series = ::gr::signal_hound::vsg_series;


    py::class_<vsg_series,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<vsg_series>>(m, "vsg_series", D(vsg_series))

        .def(py::init(&vsg_series::make),
             py::arg("center"),
             py::arg("samplerate"),
             py::arg("level"),
             py::arg("ioffset"),
             py::arg("qoffset"),
             D(vsg_series, make))


        .def("set_center",
             &vsg_series::set_center,
             py::arg("center"),
             D(vsg_series, set_center))


        .def("set_samplerate",
             &vsg_series::set_samplerate,
             py::arg("samplerate"),
             D(vsg_series, set_samplerate))


        .def("set_level",
             &vsg_series::set_level,
             py::arg("level"),
             D(vsg_series, set_level))


        .def("set_ioffset",
             &vsg_series::set_ioffset,
             py::arg("ioffset"),
             D(vsg_series, set_ioffset))


        .def("set_qoffset",
             &vsg_series::set_qoffset,
             py::arg("qoffset"),
             D(vsg_series, set_qoffset))

        ;
}
